spring:
  application:
    name: lab3
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:ai}/${DB_NAME:ai}
    username: ${DB_USER:ai}
    password: ${DB_PASS:ai}

  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      flyway:
        enabled: true

langchain4j:
  pgvector:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    database: ${DB_NAME:ai}
    user: ${DB_USER:ai}
    password: ${DB_PASSWORD:ai}
    table: game_vectors
  ollama:
    embedding-model:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      model-name: nomic-embed-text
      timeout: 999999999
    chat-model:
      base-url: https://ollama.com
      model-name: deepseek-v3.1:671b
      custom-headers:
        Authorization: Bearer acdb59cc10304dd4bc6e58382510d9e6.O5GFrYpgz5KC2QbztKctPJND
